[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']


fs_permissions = [{ access = "read-write", path = "./"}]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink-brownie-contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@ds-test/=lib/openzeppelin-contracts/lib/forge-std/lib/ds-test/src/",
    "@erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
    "@solidity-bytes-utils/=lib/solidity-bytes-utils/contracts",
    "@forge-std/=lib/forge-std/src/"]

[rpc_endpoints]
default_network = "http://127.0.0.1:8545"
localhost = "http://127.0.0.1:8545"

[etherscan]
polygonMumbai = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }


[fmt]
line_length = 80
multiline_func_header = "params_first"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
